version: "3.5"

services:
  db:
    container_name: db
    restart: always
    image: debezium/postgres:11-alpine
    volumes:
      - postgres-volume-pgdata:/var/lib/postgresql/data
    env_file:
      - linx.service.env
    networks:
      - linx-network

  api:
    build: ./../
    container_name: api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
    networks:
      - linx-network

  products:
    build: ./../products
    container_name: products
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - REDIS_HOST=redis
    networks:
      - linx-network

  catalog:
    build: ./../products-catalog
    container_name: catalog
    ports:
      - "3002:3002"
    networks:
      - linx-network

  redis:
    image: redis
    networks:
      - linx-network

networks:
  linx-network:
    name: linx-network
    driver: "bridge"

volumes:
  postgres-volume-pgdata:
